### ISSUE TITLE
Implementation example

### ISSUE THREAD

**Issue by camilofernandesalves** [ufoscout/docker-compose-wait#5] opened 2018-06-29 21:25 UTC
I am having a doubt about how to implement it on my own code, i have 3 images:
-Project image
-MongoDb image
-MariaDb image

I have followed the steps, but i think i am doing something wrong when implementing it.
Can you give me an example with those images of a docker-compose.yml using it on practice

**Comment by camilofernandesalves** [comment] 2018-06-29 21:29
here is some example of what is happening in mine `docker-compose up --build `
![captura de tela 2018-06-29 as 18 27 45](https://user-images.githubusercontent.com/12667754/42115668-3a7e9f5e-7bca-11e8-8633-967f1ba9fc8d.png)

**Comment by ufoscout** [comment] 2018-06-30 06:14
Hi @camilofernandesalves 
in your Dockerfile, your CMD should call 'wait' and then your application startup script or executable, for example:
`CMD /wait && /StartupOfMyApp.sh`

If your CMD contains only 'wait', then, after the waiting pause, your container will end its execution.

**Comment by jonasbn** [comment] 2018-06-30 19:50
hi @camilofernandesalves and @ufoscout 

Sorry for budding in, but I think the documentation is pretty clear, so this issue triggered curiosity. 

@camilofernandesalves what was the cause of your confusion?

@ufoscout what you describe, is that an anti-pattern which should be documented?

Have a nice weekend,

jonasbn

**Comment by ufoscout** [comment] 2018-07-09 06:04
@camilofernandesalves 
did you solve your issue?

**Comment by ufoscout** [comment] 2018-10-16 14:39
Closing for now. I'll reopen it if more feedback is provided.

**Closed by ufoscout** 2018-10-16 14:39 UTC
